# Generated by Django 3.0 on 2020-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
