# Generated by Django 3.0 on 2020-07-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Signup',
        ),
    ]
