# Generated by Django 3.0 on 2020-07-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20200703_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
